meta:
  numSensors: 2

1s:
  type: za.redbridge.simulator.khepera.BottomProximitySensor
  readingSize: 1
  bearing: 0
  orientation: 0
  fieldOfView: 0
  range: 0.1

2s:
  type: za.redbridge.simulator.sensor.TypedProximityAgentSensor
  detectables: [za.redbridge.simulator.object.RobotObject, za.redbridge.simulator.object.ResourceObject, za.redbridge.simulator.object.WallObject]
  readingSize: 1
  bearing: 0
  orientation: 0
  fieldOfView: 15
  range: 1.0
