meta:
  numSensors: 8

1s:
  type: za.redbridge.simulator.khepera.BottomProximitySensor
  readingSize: 1
  bearing: 0.0
  orientation: 0.0
  fieldOfView: 0.0
  range: 0.1

2s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 0.0
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0

3s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 1.571
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0

4s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 3.142
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0

5s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 4.712
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0

6s:
  type: za.redbridge.simulator.sensor.TypedProximityAgentSensor
  readingSize: 1
  bearing: 0.0
  orientation: 0.0
  fieldOfView: 0.2
  range: 1.0

7s:
  type: za.redbridge.simulator.sensor.TypedProximityAgentSensor
  readingSize: 1
  bearing: 1.571
  orientation: 0.0
  fieldOfView: 0.2
  range: 1.0

8s:
  type: za.redbridge.simulator.sensor.TypedProximityAgentSensor
  readingSize: 1
  bearing: 4.712
  orientation: 0.0
  fieldOfView: 0.2
  range: 1.0
