meta:
  numSensors: 9

1s:
  type: za.redbridge.simulator.khepera.BottomProximitySensor
  readingSize: 1
  bearing: 0.0
  orientation: 0.0
  fieldOfView: 0.0
  range: 0.1

2s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 0.0
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0

3s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 0.785
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0

4s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 1.570
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0

5s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 2.356
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0

6s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 3.142
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0

7s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 3.927
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0

8s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 4.712
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0

9s:
  type: za.redbridge.simulator.khepera.UltrasonicSensor
  readingSize: 1
  bearing: 5.498
  orientation: 0.0
  fieldOfView: 1.22
  range: 4.0
