3s: {type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor, sensitiveClass: za.redbridge.simulator.object.TargetAreaObject,
  readingSize: 1, bearing: 355.0, fieldOfView: 20.0, orientation: 0.0, range: 1.0,
  sensitivity: 0.8}
2s: {type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor, sensitiveClass: za.redbridge.simulator.object.ResourceObject,
  readingSize: 1, bearing: 5.0, fieldOfView: 20.0, orientation: 0.0, range: 1.0, sensitivity: 0.8}
1s: {type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor, sensitiveClass: za.redbridge.simulator.object.RobotObject,
  readingSize: 1, bearing: 0.0, orientation: 0.0, fieldOfView: 20.0, range: 1.0, sensitivity: 0.8}
meta: {numSensors: 6}
6s: {type: za.redbridge.simulator.sensor.ProximityAgentSensor, readingSize: 1, bearing: 180.0,
  fieldOfView: 10.0, orientation: 0.0, range: 1.0}
5s: {type: za.redbridge.simulator.sensor.ProximityAgentSensor, readingSize: 1, bearing: 275.0,
  fieldOfView: 10.0, orientation: 0.0, range: 1.0}
4s: {type: za.redbridge.simulator.sensor.ProximityAgentSensor, readingSize: 1, bearing: 45.0,
  fieldOfView: 10.0, orientation: 0.0, range: 1.0}
