control:
  maxEpochs: 200
  runsPerGenome: 4

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 50
  heteroTeamSize: 5


complements:
  generatorResolution: 0.25

morphology:
  morphologyFileName: configs/sensorList.yml
