control:
  maxEpochs: 200
  runsPerGenome: 3

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 50
  GAPopulationSize: 20

complements:
  generatorResolution: 0.3

morphology:
  morphologyFileName: configs/sensorList.yml
