control:
  maxEpochs: 200
  runsPerGenome: 5

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 120
  heteroTeamSize: 20
  runsPerTeam: 5

complements:
  generatorResolution: 0.50

morphology:
  morphologyFileName: configs/sensorList.yml
