control:
  maxEpochs: 1
  runsPerGenome: 1

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 5
  GAPopulationSize: 50

complements:
  generatorResolution: 1.0

morphology:
  morphologyFileName: sensorList.yml