control:
  maxEpochs: 10

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 25

morphology:
  morphologyFileName: sensorList.yml