control:
  maxEpochs: 100

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  fitnessFunction: za.redbridge.simulator.ea.CooperativeFitnessFunction

morphology:
  morphologyFileName: sensorlist.yml