control:
  maxEpochs: 150
  runsPerGenome: 4

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 60
  heteroTeamSize: 20
  runsPerTeam: 4

complements:
  generatorResolution: 0.50

morphology:
  morphologyFileName: configs/sensorList.yml
