control:
  maxEpochs: 1000
  runsPerGenome: 3

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 100
  heteroTeamSize: 5

complements:
  generatorResolution: 0.3

morphology:
  morphologyFileName: configs/sensorList.yml
