control:
  maxEpochs: 20
  runsPerGenome: 5

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 20
  GAPopulationSize: 50

complements:
  generatorResolution: 0.3

morphology:
  morphologyFileName: sensorList.yml