control:
  maxEpochs: 1
  runsPerGenome: 1

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 2
  GAPopulationSize: 20

complements:
  generatorResolution: 0.5

morphology:
  morphologyFileName: configs/sensorList.yml
