control:
  maxEpochs: 100
  runsPerGenome: 4

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 300
  heteroTeamSize: 10


complements:
  generatorResolution: 0.25

morphology:
  morphologyFileName: configs/sensorList.yml
