control:
  maxEpochs: 5
  runsPerGenome: 100

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 100
  heteroTeamSize: 20

complements:
  generatorResolution: 0.50

morphology:
  morphologyFileName: configs/sensorList.yml
