control:
  maxEpochs: 5
  runsPerGenome: 5

phenotype:
  robotPhenotype: za.redbridge.simulator.phenotype.NEATPhenotype

evolutionaryAlgorithm:
  controllerEA: NEAT
  populationSize: 10

morphology:
  morphologyFileName: sensorList.yml