meta:
  numSensors: 5

1s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.RobotObject
  readingSize: 1
  bearing: 5.0
  orientation: 0.0
  fieldOfView: 2.0
  range: 5.0
  sensitivity: 0.8

2s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.ResourceObject
  readingSize: 1
  bearing: 0.0
  fieldOfView: 2.0
  orientation: 0.0
  range: 5.0
  sensitivity: 0.8


3s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.WallObject
  readingSize: 1
  bearing: 355.0
  fieldOfView: 2.0
  orientation: 0.0
  range: 5.0
  sensitivity: 0.8


4s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: 10.0
  fieldOfView: 5.0
  range: 5.0
  orientation: 0.0

5s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: -10.0
  fieldOfView: 5.0
  range: 5.0
  orientation: 0.0

6s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: 75.0
  fieldOfView: 5.0
  range: 5.0
  orientation: 0.0

7s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: -75
  fieldOfView: 5.0
  range: 5.0
  orientation: 0.0

8s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: 140.0
  fieldOfView: 5.0
  range: 5.0
  orientation: 0.0

9s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: -140.0
  fieldOfView: 5.0
  range: 5.0
  orientation: 0.0