meta:
  numSensors: 6

1s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.RobotObject
  readingSize: 1
  bearing: 5.0
  orientation: 0.0
  fieldOfView: 10.0
  range: 0.5
  sensitivity: 0.8

2s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.ResourceObject
  readingSize: 1
  bearing: 0.0
  fieldOfView: 10.0
  orientation: 0.0
  range: 0.5
  sensitivity: 0.8


3s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.WallObject
  readingSize: 1
  bearing: 355.0
  fieldOfView: 10.0
  orientation: 0.0
  range: 0.5
  sensitivity: 0.8

4s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.TargetAreaObject
  readingSize: 1
  bearing: 350.0
  fieldOfView: 10.0
  orientation: 0.0
  range: 0.5
  sensitivity: 0.8

5s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: 10.0
  fieldOfView: 5.0
  range: 1.0
  orientation: 0.0

6s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: -10.0
  fieldOfView: 5.0
  range: 1.0
  orientation: 0.0