meta:
  numSensors: 5

1s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.RobotObject
  readingSize: 1
  bearing: 5.0
  orientation: -5.0
  fieldOfView: 10.0
  range: 4.0
  sensitivity: 0.8

2s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.ResourceObject
  readingSize: 1
  bearing: -5.0
  fieldOfView: 10.0
  orientation: 5.0
  range: 4.0
  sensitivity: 0.8

3s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.WallObject
  readingSize: 1
  bearing: 10.0
  fieldOfView: 10.0
  orientation: -10.0
  range: 4.0
  sensitivity: 0.8

4s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.TargetAreaObject
  readingSize: 1
  bearing: -10.0
  fieldOfView: 10.0
  orientation: 10.0
  range: 4.0
  sensitivity: 0.8

5s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: 180.0
  fieldOfView: 10.0
  range: 4.0
  orientation: 0.0