meta:
  numSensors: 6

1s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.ResourceObject
  readingSize: 1
  bearing: 0.0
  orientation: 0.0
  fieldOfView: 20.0
  range: 10.0
  sensitivity: 0.8

2s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.ResourceObject
  readingSize: 1
  bearing: 30.0
  fieldOfView: 20.0
  orientation: 0.0
  range: 10.0
  sensitivity: 0.8

3s:
  type: za.redbridge.simulator.sensor.ThresholdedObjectProximityAgentSensor
  sensitiveClass: za.redbridge.simulator.object.ResourceObject
  readingSize: 1
  bearing: 330.0
  fieldOfView: 20.0
  orientation: 0.0
  range: 10.0
  sensitivity: 0.8

4s:
  type: za.redbridge.simulator.sensor.FilteredProximityAgentSensor
  whiteList: za.redbridge.simulator.object.ResourceObject za.redbridge.simulator.object.RobotObject
  readingSize: 1
  bearing: 90.0
  fieldOfView: 10.0
  orientation: 0.0
  range: 10.0

5s:
  type: za.redbridge.simulator.sensor.FilteredProximityAgentSensor
  whiteList: za.redbridge.simulator.object.ResourceObject za.redbridge.simulator.object.RobotObject
  readingSize: 1
  bearing: 180.0
  fieldOfView: 10.0
  orientation: 0.0
  range: 10.0

6s:
  type: za.redbridge.simulator.sensor.FilteredProximityAgentSensor
  whiteList: za.redbridge.simulator.object.ResourceObject za.redbridge.simulator.object.RobotObject
  readingSize: 1
  bearing: 270.0
  fieldOfView: 10.0
  orientation: 0.0
  range: 10.0
