meta:
  numSensors: 5

1s:
  type: za.redbridge.simulator.sensor.LinearObjectProximityAgentSensor
  readingSize: 4
  bearing: 0
  fieldOfView: 10.0
  range: 2.0
  orientation: 0.0
  robotSensorDetectivity: 1.0
  robotSensorGain: 1.0
  resourceSensorDetectivity: 1.0
  resourceSensorGain: 1.0
  targetAreaSensorDetectivity: 1.0
  targetAreaSensorGain: 1.0

2s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: 180.0
  fieldOfView: 10.0
  range: 2.0
  orientation: 0.0

3s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: 90.0
  fieldOfView: 10.0
  range: 2.0
  orientation: 0.0

4s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: -90.0
  fieldOfView: 10.0
  range: 2.0
  orientation: 0.0

5s:
  type: za.redbridge.simulator.sensor.ProximityAgentSensor
  readingSize: 1
  bearing: 0.0
  fieldOfView: 10.0
  range: 2.0
  orientation: 0.0