---
resourceProperties:
  smallResources: 20
  smallObjectWidth: 0.4
  smallObjectHeight: 0.4
  smallObjectMass: 5.0
  maxSmallObjectPushingBots: 1
  largeResources: 1
  largeObjectWidth: 4.0
  largeObjectHeight: 4.0
  largeObjectMass: 10.0
  maxLargeObjectPushingBots: 3
scoring:
  fitnessFunction: za.redbridge.simulator.ea.CooperativeFitnessFunction
factories:
  resourceFactory: za.redbridge.simulator.factories.ConfigurableResourceFactory
  robotFactory: za.redbridge.simulator.factories.HomogeneousRobotFactory
robots:
  numRobots: 10
  mass: 0.7
  radius: 0.15
  colour: 0, 0, 0
