---
simulation:
  iterations: 10000
resourceProperties:
  smallResources: 10
  smallObjectWidth: 0.3
  smallObjectHeight: 0.3
  smallObjectMass: 1.0
  maxSmallObjectPushingBots: 1
  largeResources: 10
  largeObjectWidth: 0.7
  largeObjectHeight: 0.7
  largeObjectMass: 3.0
  maxLargeObjectPushingBots: 2
scoring:
  fitnessFunction: za.redbridge.simulator.ea.DefaultFitnessFunction
factories:
  resourceFactory: za.redbridge.simulator.factories.ConfigurableResourceFactory
  robotFactory: za.redbridge.simulator.factories.HomogeneousRobotFactory
robots:
  numRobots: 20
  mass: 0.7
  radius: 0.15
  colour: 0, 0, 0
