---
simulation:
  iterations: 10000
resourceProperties:
  smallResources: 0
  smallObjectWidth: 0.4
  smallObjectHeight: 0.4
  smallObjectMass: 1.0
  maxSmallObjectPushingBots: 1
  largeResources: 40
  largeObjectWidth: 0.6
  largeObjectHeight: 0.6
  largeObjectMass: 4.5
  maxLargeObjectPushingBots: 3
teams:
  heterogeneousTeams: true
  teamSize: 5
scoring:
  individualScoring: true
factories:
  resourceFactory: za.redbridge.simulator.factories.ConfigurableResourceFactory
robots:
  numRobots: 20
  mass: 0.7
  radius: 0.15
  colour: 0, 0, 0
